-- Legacy compatibility marker.
-- Canonical retention purge is defined in 20260902120000_tracking_privacy_retention.sql.
-- A later repair migration ensures legacy databases contain the canonical function.